### Creating tensors in PyTorch

In [1]:
# Import torch
import torch

# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.6407, 0.1721, 0.4835],
        [0.9452, 0.7765, 0.0634],
        [0.1778, 0.4532, 0.4072]])
torch.Size([3, 3])


### Matrix multiplication

In [2]:
tensor_of_ones = torch.ones(3, 3)
tensor_of_identity = torch.eye(3)
matrices_multiplied = torch.matmul(tensor_of_ones, tensor_of_identity)
element_multiplication = torch.mul(tensor_of_ones, tensor_of_identity)
print(matrices_multiplied)
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Forward pass

In [3]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x, y)

# Multiply elementwise z with q
f = torch.mul(z, q)

mean_f = torch.mean(f)
print(mean_f)

tensor(125.1861)


### Backpropagation using PyTorch

In [4]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True )
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x+y
f = q*z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


### Calculating gradients in PyTorch

In [5]:
# Multiply tensors x and y
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)
x = torch.tensor(x, requires_grad=True)
y = torch.tensor(y, requires_grad=True)
z = torch.tensor(z, requires_grad=True)

q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = q * z

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

/tmp/ipykernel_196/1803197281.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, requires_grad=True)
/tmp/ipykernel_196/1803197281.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, requires_grad=True)
/tmp/ipykernel_196/1803197281.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.tensor(z, requires_grad=True)


### First neural network

In [6]:
# Initialize the input layer
input_layer = torch.rand(784)

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([20863.6484, 18681.2383, 20542.0684, 19424.6113, 19829.8477, 18185.8027,
        18608.3379, 19761.5410, 18461.0742, 20700.3926])


### First PyTorch neural network

You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.

In [7]:
import torch.nn as nn

In [8]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

In [9]:
net=Net()
result = net(input_layer)
print(result)

tensor([ 0.2139,  0.3245, -0.1315, -0.1950, -0.2373,  0.1256,  0.0031,  0.0687,
         0.0771, -0.1181], grad_fn=<AddBackward0>)


In [10]:
input_layer.shape, result.shape

(torch.Size([784]), torch.Size([10]))

In [11]:
import torch.nn as nn

In [12]:
# Instantiate ReLU activation function as relu
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers
weight_1 = torch.rand(10, 6)
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(result, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

tensor([0.3015, 0.1602], grad_fn=<SqueezeBackward3>)


In [43]:
a=-1.2
b=0.12
c=4.8

In [44]:
e=(1+1/1000)**1000

In [45]:
print(e)

2.7169239322355936


In [46]:
d=e**a

In [47]:
f=e**b

In [48]:
g=e**c

In [49]:
h=d+f+g

In [50]:
aa=d/h
bb=f/h
cc=g/h
print(aa, bb, cc)

0.0024572314097191877 0.009192387653911135 0.9883503809363697


In [51]:
1-cc

0.011649619063630268

In [41]:
e**1

2.7169239322355936

In [42]:
e**0

1.0

### Calculating loss function in PyTorch


In [52]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])
print(ground_truth)
# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor([2])
tensor(0.0117)


### Loss function of random scores


If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.

In [53]:
# Initialize logits and ground truth
logits = torch.rand(1, 1000)
ground_truth = torch.tensor([111]) #____

# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(7.2581)
